version: '3.3'

services:
  mstream-server: &mstream-server
    image: quay.io/kozhukalov/go-adc
    restart: always
    volumes:
    - /home/pmtlab/tmp:/data
    - /home/pmtlab/.go-adc:/root/.go-adc
    network_mode: host
    command: go-adc mstream start
  control-server:
    <<: *mstream-server
    command: go-adc control start
  discover-server:
    <<: *mstream-server
    command: go-adc discover start
